package com.virtualmento.logging.entity;

public enum SecurityEventType {

    REGISTER,
    EMAIL_VERIFIED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,

    TOKEN_REFRESHED,
    TOKEN_REFRESH_FAILED,

    LOGOUT,
    LOGOUT_OTHER_DEVICES,
    LOGOUT_ALL_DEVICES,
    SESSION_REVOKED,

    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    ACCOUNT_DISABLED,
    ACCOUNT_ENABLED
}