spring:
  jackson:
    time-zone: Asia/Kolkata

  application:
    name: virtualmento

  datasource:
    url: jdbc:postgresql://localhost:5432/pitchpilot
    username: postgres
    password: postgres

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

server:
  port: 8080

jwt:
  issuer: virtualmento-api
  access-token-expiration: 900
  public-key: ${JWT_PUBLIC_KEY:MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuoZMqcNaLyHIWjxb0x3/elTwBYZr6QMNPM/rqzpo0t1Mvoy25i61h1nH+N907nDO3DqzKhbqAELCBakftGrH6n9mXne9qqTf5KVK5zf7f1Z18vr+Kj1+B4jTDuk727s9Oxb3j2hOzQjd2VA7yp85tW4PHujY0DEG11jE4ChAvYDk4yF/bBP/5pUEw/kZHBTz0FERDMX2bDAJOTWT/Bekl9+//PqmsyIo5gkOAVSOyWC+JsAC8sdPNiPqK4A/TeDtyY01jmO8nrcn1m/k3ySqJdu91z6HJJ2uBolscZSjgf7FW4np/ybuwCWENTTMO+PuXKjNCWzpE+Ij7ypzPoZkz+Zogcb8XFMMIyc7P555nZpO3OK7PIKWbRvmRlFlFwotx6BK2G0cLY7ntgZr1n77mF5qTkyQelsZq2uyJwxq54oNJx6Iq/BaMIfGOMCrQ60/rtD+aBKkYSBvkrj0EWbs468n0QY3co+3PHestE+yyP+nZmDiaAqRtxkgY+9dtOMD73G9VZDbGEMtzQyqGMnlRFbKnUntkIKvGfAVWVeo0+gkqFfDeqrhEQw8omyhjTtKsg9vh1PWGYUyN2Z7NuveTyP+d84UAu3gNf9RylNKYBWgeBC5yxKXf6pyK0p7c+mX0tVR4p5Z5V3P007dvEr5JvE2QC0bgdepbJW/AaFi/QkCAwEAAQ==}
  private-key: ${JWT_PRIVATE_KEY:MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC6hkypw1ovIchaPFvTHf96VPAFhmvpAw08z+urOmjS3Uy+jLbmLrWHWcf433TucM7cOrMqFuoAQsIFqR+0asfqf2Zed72qpN/kpUrnN/t/VnXy+v4qPX4HiNMO6Tvbuz07FvePaE7NCN3ZUDvKnzm1bg8e6NjQMQbXWMTgKEC9gOTjIX9sE//mlQTD+RkcFPPQUREMxfZsMAk5NZP8F6SX37/8+qazIijmCQ4BVI7JYL4mwALyx082I+orgD9N4O3JjTWOY7yetyfWb+TfJKol273XPockna4GiWxxlKOB/sVbien/Ju7AJYQ1NMw74+5cqM0JbOkT4iPvKnM+hmTP5miBxvxcUwwjJzs/nnmdmk7c4rs8gpZtG+ZGUWUXCi3HoErYbRwtjue2BmvWfvuYXmpOTJB6Wxmra7InDGrnig0nHoir8Fowh8Y4wKtDrT+u0P5oEqRhIG+SuPQRZuzjryfRBjdyj7c8d6y0T7LI/6dmYOJoCpG3GSBj71204wPvcb1VkNsYQy3NDKoYyeVEVsqdSe2Qgq8Z8BVZV6jT6CSoV8N6quERDDyibKGNO0qyD2+HU9YZhTI3Zns2695PI/53zhQC7eA1/1HKU0pgFaB4ELnLEpd/qnIrSntz6ZfS1VHinlnlXc/TTt28Svkm8TZALRuB16lslb8BoWL9CQIDAQABAoICAAQ4Ng3wGf9EyyDEH/VUcXtdu7P69hV7yMX2U9ftjBdbGMRFxXx1vuG3OvzLEfzekfDC+4XJUMAH7UDjXNDVdTzS5tNeb5dnlUYO+YpmBpCQpD3xMM9D/AYlHFXdxQl5QKRwe6djnhwUJi/8mUGsnPRZBKANIfHXGMHF47xIxNV/T+OV1ilb1syV/0PaA9f8tFr4foN/YKNSvzQAst6U1VfMi24TEzLXDr2iI6ONkLuxrn43a/RR5HLugzq6iGlqsXkUsqBhlWUyHQVZm3/zIc3rR5iR36JJK+RAzHJ8Vj+XrnTIl6x6lROaiwAIzVGnMXT9/5dwk+GWhSbBBdblWOyeJilWnaq8wqpgJk6YDT+G8HjnCQfMCG01B18p1Uq4/P2OcV+23R7QBdds1Dn7ZJ9NwxfBDVg2XMnqKNMYpQvMumZsMPpkRgFUbuufan2PRXlyxDhTrkCs+fxP4f1Okil625Z7Puw0QTgMoxGTQX3Ek1Qigog/1IL2kNOQiQSkiQ3qGANjFxKOSbj4fRr/K1cvNIN230cTjE+s8RLHUalV5KfaxerOts1EP3Qh0ODBCHoBxa/CE9PW1gTMtbUAmqL947+CB+gDMiLP8DxVtc//abIgfvt3qJWvqv6X5bGy3GD2ceQGO3zRoF53PK6DP1llkqNabEYKH5fglGRVYM6hAoIBAQDDxCZ8TCVpOylVdlYjkCzGoPlDo+QQHdDZQJBjEz8bgpMBd3jShG6A1EqtdIJvrVKwsaPIidU9VDe8zRYSjqvbuPdvYJ+JVeT301pBW1Tj5feNZzoUNDxpUX+ohx2BLGKGJZZY1sBN4rgH46ulxTXfoG3mxHaajVLLmMYw4luvIgd3ClSS39y520D4yv1XsC2TiSrc65i6nyzqyJ6tmsGhdtR56Xa04muxECGoh1zF/RjNCptOCVm1DTaPpsZO0nVl+p3i2LyiKc5pu0TYav6TUZwF3Z0eiQzzAqz/X287rZAnBdss8bjgOAlrZiRFaBC/w2nhY/JnoqrWer6CEbRZAoIBAQDz6jgE089oxoUndGevLBtsPBUtSI6cppX+iyTD3VaNjCGfqGxMILAFsGay+UoGMZbPoEJP626sszOaKWK9xlebPjASQh81fgLDWOTbWvzqLlKvNTOB/FWZbuvY5x0n0Y+7rnfU6/NAcppra1oFvBJJQ8IDO4aim6i16tKBNlmNm94j5NZaaSud/raw5zX9d2B8T560/6yrsQhyOhX0RVtvrPbyFEc4/J7QmHyTSsUWE/3MLne2J5bCzSl2wFg2iqz4+/C/65CVnnz7ld6wRkzoZT4O12iYHT0D5dfmXQ5EfFeiInMGYJTv7TdjHjFz4nKZrbsalZ9XVxeXtQgfbDgxAoIBAFUDXWMk/ioQkwaV+RpAhfFL/nMtPODy0btGmm0r8n/T2FsOst1YvVQc3MEuk2ZD8mDhA6sWkA+t/vZyaV9trZwhWvJ3F1DgiCpHEi7HprnBKBuz9DjJ5mImDjX1Vw69Y5u1vvCdca1hA2IJsISwe5C9bnyEXK0JKidYFNkts3r+YBeF2OxfYs8jM7fXDuWBkIk9S+vcM9r3PN5IeQAS8HtZyzOV+wLaQMIHq1YwUk14d8izDnZ5AQfq0QLY/c1E/85lYyMb0+7oEMdBl8gTzrHTAtpZPt3/zivJwa60lu1nle4cUO3Xmt1j+FM3bBDn/D4KcnR6ns36ig3SB+EcJyECggEAAfzIlBF9wSbM8vNZ3O2JE6qxqXrL3q7kzfwoQohNKj4YEAr5Ru2FQaacT50EY2SIDA0MPUZ30mRraTgpG86/6/3nul5bjr4GG71fsAHfybCy78aJMufxcpyaw1uuuyJT/31+cHeztbS5WWK4iw9rPrmUnR4hDLYj+8d8C517wVGhz70PmhD9T/5BUtOvdu9AFAM6EdN7frKklPmwMBtYkWJhaLuNkQNN7/kuGq0jSfjDuqQuSYetDM1LJzKOBXO/0Q+MeKPcu7tc3VftRpZsDgC1Lr3Glma2lo+K4M+lTB2PQTzynvyuef3+04ntcTpJIMNvoNnTQIzvHkdVV5w0IQKCAQEArf61fH/CQZ2Ud9AFOxV9INfz6dl2CwUTJUzjI9iAGHZtobFjfSTABIzv/FJ1DOd9ADE2kSwIcF/l+TEtk0gkIRhJC72exFg6G7H+tOPQmJt53SB/Z9/9SW6vG7/uDyXJAzODCnkafd7JnB5vyHkBzkL5LRY9JvH80UKmCKGg0AeOUC+1O6QAKuXg8vuistighIayiIDZ4QOyYCOz/C3xsGH2ZgHbJEmPw5X8PvWQXOoqHqcjafpTQ9wiITQI6U0B0S1RJP0sy9FhVr8vhAB/+xiyHzpphz7tdPiJVLOGLSCiMSS/NHwq3H6A/FJMIeN+WIVR52G0ecp4IiuVXJYHnA==}

security:
  otp:
    expiration-seconds: ${OTP_EXPIRATION_SECONDS:300}
    max-attempts: ${OTP_MAX_ATTEMPTS:5}
    resend-cooldown-seconds: ${OTP_RESEND_COOLDOWN_SECONDS:60}
